export enum UserRole {
    SUPER_ADMIN = 'SUPER_ADMIN',
    MANDAL_OFFICER = 'MANDAL_OFFICER',
    DISTRICT_OFFICER = 'DISTRICT_OFFICER',
    STATE_OFFICER = 'STATE_OFFICER',
    APPLICANT = 'APPLICANT',
}

export const ROLES = {
    SUPER_ADMIN: UserRole.SUPER_ADMIN,
    MANDAL_OFFICER: UserRole.MANDAL_OFFICER,
    DISTRICT_OFFICER: UserRole.DISTRICT_OFFICER,
    STATE_OFFICER: UserRole.STATE_OFFICER,
    APPLICANT: UserRole.APPLICANT,
} as const;
