export const APPLICATION_STATUS = {
    DRAFT: 'DRAFT',
    SUBMITTED: 'SUBMITTED',
    MANDAL_REVIEW: 'MANDAL_REVIEW',
    DISTRICT_REVIEW: 'DISTRICT_REVIEW',
    STATE_REVIEW: 'STATE_REVIEW',
    APPROVED: 'APPROVED',
    REJECTED: 'REJECTED',
    CORRECTION_REQUIRED: 'CORRECTION_REQUIRED',
} as const;

export type ApplicationStatus = typeof APPLICATION_STATUS[keyof typeof APPLICATION_STATUS];

export const APPROVAL_ACTION = {
    APPROVE: 'APPROVE',
    REJECT: 'REJECT',
    REQUEST_CORRECTION: 'REQUEST_CORRECTION',
} as const;

export type ApprovalAction = typeof APPROVAL_ACTION[keyof typeof APPROVAL_ACTION];
